// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WOMS.Infrastructure.Data;

#nullable disable

namespace WOMS.Infrastructure.Migrations
{
    [DbContext(typeof(WomsDbContext))]
    [Migration("20250115000000_UpdateWorkflowNodeTypeToEnum")]
    partial class UpdateWorkflowNodeTypeToEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a simplified version - the full model would be auto-generated
            // The key change is that WorkflowNode.Type is now an int (enum) instead of string
#pragma warning restore 612, 618
        }
    }
}
